### ISSUE TITLE
Unable to create the cache directory

### ISSUE THREAD

**Issue by vnetmx** [elkarbackup/elkarbackup-docker#15] opened 2017-05-30 17:22 UTC
Hola, 

Tengo este problema al ejecutar un Job,
Exception Unable to create the cache directory (/var/cache/elkarbackup/prod/twig/f6). running command {"command":"elkarbackup:run_job","client":"1","job":"3"}:

El directorio twig tiene permisos para www-data como debe ser:

drwxr-xr-x+  11 www-data    www-data      4096 May 30 12:17 twig

Ejecuto otros jobs del mismo cliente y todo esta en orden, solo ste Job en particular me esta dando problemas.

Saludos

**Comment by vnetmx** [comment] 2017-05-30 17:35
I changed the permision to 777 on twig directory and the job worked but was created by a elkarbackup user and not www-data, is it ok?

**Comment by xezpeleta** [comment] 2017-05-30 19:20
Apparently there is a problem related to ACLs and permissions.

What Linux distribution are you using in your host machine? What is your Docker version?

**Comment by vnetmx** [comment] 2017-05-30 20:14
Hola, estas son las versiones:

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

root@cloud:~# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by xezpeleta** [comment] 2017-06-04 11:12
I can't reproduce the problem. Did you only see this issue with one job?

Can you delete (or move) its backup folder and try again?

**Comment by vnetmx** [comment] 2017-06-04 13:07
No, el problema apareció con cualquier Job que se quisiera crear o ejecutar en ese tiempo, al cambiar los permisos a 777 se solucionó., pero como te comento se creo con elkarbackup user y no www-data como están las demás estructuras.

Otras implementaciones q tengo han estado trabajando bien, solo esta como que se le safo un tornillo.

**Comment by xezpeleta** [comment] 2017-06-15 15:46
En la instalación por defecto, el propietario de los ficheros en el directorio de backups (`/var/spool/elkarbackup/backup`) es **elkarbackup** y después se utilizan las ACLs para permitir acceso a otros usuarios como www-data.

Si en vez de lanzar la tarea usando la web, lo haces a mano o por comando por CLI, tienes que tener cuidado con el usuario.

¿Ha podido ser ese la causa del problema?

Gracias

**Comment by xezpeleta** [comment] 2018-02-13 14:19
He actualizado la imagen de docker.

**Comment by ffabreti** [comment] 2018-06-21 19:26
I am having the same problem:

`Exception Unable to create the cache directory (/var/cache/elkarbackup/prod/twig/f6). running command {"command":"elkarbackup:run_job","client":"1","job":"2"}:`

Docker version | 18.05.0-ce

docker inspect:

{
    "AppArmorProfile": "",
    "Args": [],
    "Config": {
        "ArgsEscaped": true,
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": null,
        "Domainname": "",
        "Entrypoint": [
            "/entrypoint.sh"
        ],
        "Env": [
            "MYSQL_ROOT_PASSWORD=my-great-passwd",
            "EB_VERSION=1.2.7",
            "EB_DB_HOST=172.17.0.3",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "ExposedPorts": {
            "443/tcp": {},
            "80/tcp": {}
        },
        "Hostname": "3db9b81d4589",
        "Image": "elkarbackup/elkarbackup:latest",
        "Labels": {},
        "OnBuild": null,
        "OpenStdin": false,
        "StdinOnce": false,
        "Tty": true,
        "User": "",
        "Volumes": {
            "/etc/elkarbackup": {},
            "/var/lib/elkarbackup/.ssh": {},
            "/var/spool/elkarbackup": {}
        },
        "WorkingDir": ""
    },
    "Created": "2018-06-20T16:00:05.455806758Z",
    "Driver": "overlay2",
    "ExecIDs": [
        "cdebbbcaeac09d65641870b316da6ae14bf573d929bfceed414b8e16b4de4951",
        "1d88830bbd52a127cc14fa7a742c17224a5bba8771abcac985b24d6fee8bb255"
    ],
    "GraphDriver": {
        "Data": {
            "LowerDir": "/var/lib/docker/overlay2/bc7d53b3b21b2660f4e6e8dc7ef8539168298c959b0b73e4fce30c08d03cddd8-init/diff:/var/lib/docker/overlay2/8c0e99f46ca4b012691c9b5b9e348b009e48b49e892d5e9010e9a7abd12b63fb/diff:/var/lib/docker/overlay2/122d1f236850ca44d2e39955a2b78734082a5080133705e180eed8fef858ab2b/diff:/var/lib/docker/overlay2/dc92ae8e5fa701dccfda44b06c1b565ab452880d92c4b0b6c8e1f58192b0736d/diff:/var/lib/docker/overlay2/2e30066c683ad798d2c79d6624874ced2418d65ee81dc327af4c7e6cc1c9badd/diff:/var/lib/docker/overlay2/ddea4cac56fc2b9703a0f08add0b2d470a69b99c63fd00ece8db395f0ad0aeb4/diff:/var/lib/docker/overlay2/855820c2f96847bf99e7a9066bb3b24d4bc6c99a44e802a4e4641885bc140017/diff:/var/lib/docker/overlay2/b111d736195a3e7fe515a8e1f85ba3c4c5635b9d42d619958fa3d20cda668e8c/diff:/var/lib/docker/overlay2/90947a53f5bc9089ded5341b3c09ea41f6523d4ce50d72e84e6931e414d95aa3/diff:/var/lib/docker/overlay2/1b9efc45ad48f87907371d920d707b9d44ce770aeb67903425a27bac30074db7/diff:/var/lib/docker/overlay2/80bc691fecb22858d630a38eb6101d611eda79b58ecdeb8955e3541336bde311/diff:/var/lib/docker/overlay2/e546d1a874f00fbc1536b9ca613164e884002ed59bf1538715df27efa0136a5a/diff:/var/lib/docker/overlay2/09bc9db326dec578f3ad25625c6b1497574e5f2c503f6cbed66012752b658b0e/diff:/var/lib/docker/overlay2/add71a3a2126f3cd62b63652a0ba56af0358e9d0877674d104b0d9a1db056a44/diff:/var/lib/docker/overlay2/86b1cd14eadbb1c29482feaeeb7bc19f5de6744e597caef43eaf199eaf99f07f/diff:/var/lib/docker/overlay2/68d66beebc00dc5ba61cdfb1f36e4b0a7ca99bbc71b28d9e768ffa5166b4632d/diff:/var/lib/docker/overlay2/f16b973962e87c0d2c3eba2d76afe751c9afd19539b542c1c1ea1daaebab5279/diff",
            "MergedDir": "/var/lib/docker/overlay2/bc7d53b3b21b2660f4e6e8dc7ef8539168298c959b0b73e4fce30c08d03cddd8/merged",
            "UpperDir": "/var/lib/docker/overlay2/bc7d53b3b21b2660f4e6e8dc7ef8539168298c959b0b73e4fce30c08d03cddd8/diff",
            "WorkDir": "/var/lib/docker/overlay2/bc7d53b3b21b2660f4e6e8dc7ef8539168298c959b0b73e4fce30c08d03cddd8/work"
        },
        "Name": "overlay2"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [
            "/srv/backup/elkarbackup/var-spool:/var/spool/elkarbackup",
            "/srv/backup/elkarbackup/etc-elkarbackup:/etc/elkarbackup",
            "/srv/backup/elkarbackup/var-lib-elkarbackup-.ssh:/var/lib/elkarbackup/.ssh"
        ],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": [],
        "CapAdd": null,
        "CapDrop": null,
        "Cgroup": "",
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "Devices": [],
        "DiskQuota": 0,
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": null,
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "IpcMode": "shareable",
        "Isolation": "",
        "KernelMemory": 0,
        "Links": [
            "/mysql1:/elkarbackup/mysql"
        ],
        "LogConfig": {
            "Config": {},
            "Type": "json-file"
        },
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "bridge",
        "OomKillDisable": false,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": 0,
        "PortBindings": {
            "443/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "4443"
                }
            ]
        },
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "unless-stopped"
        },
        "Runtime": "runc",
        "SecurityOpt": null,
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/3db9b81d45894ad1b2b7af38cbcb71c3ee875022857c40e8cebbe007f8a9441e/hostname",
    "HostsPath": "/var/lib/docker/containers/3db9b81d45894ad1b2b7af38cbcb71c3ee875022857c40e8cebbe007f8a9441e/hosts",
    "Id": "3db9b81d45894ad1b2b7af38cbcb71c3ee875022857c40e8cebbe007f8a9441e",
    "Image": "sha256:1bfcc3a37debe291329f1a4f2500383b4bc6d3137d4fb34c5a57b28551e68fcf",
    "LogPath": "/var/lib/docker/containers/3db9b81d45894ad1b2b7af38cbcb71c3ee875022857c40e8cebbe007f8a9441e/3db9b81d45894ad1b2b7af38cbcb71c3ee875022857c40e8cebbe007f8a9441e-json.log",
    "MountLabel": "",
    "Mounts": [
        {
            "Destination": "/var/spool/elkarbackup",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/srv/backup/elkarbackup/var-spool",
            "Type": "bind"
        },
        {
            "Destination": "/etc/elkarbackup",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/srv/backup/elkarbackup/etc-elkarbackup",
            "Type": "bind"
        },
        {
            "Destination": "/var/lib/elkarbackup/.ssh",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/srv/backup/elkarbackup/var-lib-elkarbackup-.ssh",
            "Type": "bind"
        }
    ],
    "Name": "/elkarbackup",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "c59ad1d771cd75b9ed6d231a06fb2293f639abbe8e5b4249c4b8bd0e98d67cab",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.4",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:04",
        "Networks": {
            "bridge": {
                "Aliases": null,
                "DriverOpts": null,
                "EndpointID": "c59ad1d771cd75b9ed6d231a06fb2293f639abbe8e5b4249c4b8bd0e98d67cab",
                "Gateway": "172.17.0.1",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": null,
                "IPAddress": "172.17.0.4",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "02:42:ac:11:00:04",
                "NetworkID": "8961a9100499e6357217280cf3db9cf82f6e729d273140e01985bfbe76fc4b60"
            }
        },
        "Ports": {
            "443/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "4443"
                }
            ],
            "80/tcp": null
        },
        "SandboxID": "dc2772b2f503e9e01d2e04be1310a24ac098eb261cd5dec41b59b504919add95",
        "SandboxKey": "/var/run/docker/netns/dc2772b2f503",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "/entrypoint.sh",
    "Platform": "linux",
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/3db9b81d45894ad1b2b7af38cbcb71c3ee875022857c40e8cebbe007f8a9441e/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "2018-06-21T18:41:54.080132336Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 28056,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2018-06-21T18:41:55.24429785Z",
        "Status": "running"
    }
}

**Comment by xezpeleta** [comment] 2018-06-21 21:24
Hola,

¿ Estás usando la imagen elkarbackup/elkarbackup:1.2.7 ?

Aquí tienes un ejemplo:
https://hub.docker.com/r/elkarbackup/elkarbackup/

**Comment by xezpeleta** [comment] 2018-06-21 21:38
Prueba a hacer un `docker pull elkarbackup/elkarbackup" por si acaso

**Comment by ffabreti** [comment] 2018-07-26 19:17
Yes, I am using 1.2.7, I've opened another issue https://github.com/elkarbackup/elkarbackup/issues/307 
but now I see it was on elkarbackup repo, not elkarbackup-docker.

**Comment by xezpeleta** [comment] 2018-10-16 15:24
I'm closing this issue because we've released a completely new docker image:

https://hub.docker.com/r/elkarbackup/elkarbackup/

**Closed as completed by xezpeleta** 2018-10-16 15:24 UTC
